baseURL: "/"
title: <fellas>
paginate: 5
theme: hugo-PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        profileMode:
          enabled: true
          title: fellas

          imageUrl: "logo.png"
          imageTitle: <fellas>
          imageWidth: 160
          imageHeight: 160

          subtitle: üê∏ a mediumcore wow guild on üë∫zandalar tribe-eu üêª

          buttons:
            - name: apply
              url: "https://tally.so/r/mZ6zym"
            - name: logs
              url: "https://classic.warcraftlogs.com/guild/id/606112"
            - name: loot
              url: "https://rclootcouncil.com/"

        menu:
            main:
                - name: info
                  url: posts
                  weight: 5

      #          - name: Archives
      #            url: archives
      #            weight: 5
      #          - name: Search
      #            url: search/
      #            weight: 10
      #          - name: Tags
      #            url: tags/
      #            weight: 10
      #          - name: Categories
      #            url: categories/
      #            weight: 10

    # fr:
      #  languageName: ":fr:"
      #  languageAltTitle: French
      #  weight: 2
      #  title: PaperModL2
      #  profileMode:
      #      enabled: true
      #      title: PaperMod
            # imageUrl: "#"
            # imageTitle: my image
            # imageWidth: 120
            # imageHeight: 120
      #      subtitle: "‚òÑÔ∏è Fast | ‚òÅÔ∏è Fluent | üåô Smooth | üì± Responsive"
      #      buttons:
      #          - name: Blog
      #            url: posts
      #          - name: Tags
      #            url: tags
      #  menu:
      #      main:
      #          - name: Archive
      #            url: archives/
      #            weight: 5
      #          - name: Tags
      #            url: tags
      #            weight: 10
      #          - name: Categories
      #            url: categories
      #            weight: 10
      #          - name: Series
      #            url: series
      #            weight: 10
      #          - name: NullLink
      #            url: "#"
      #          - name: NullLink2
      #            url: "#"
      #          - name: NullLink3
      #            url: "#"

    #fa:
    #    languagedirection: rtl
    #    weight: 3
    #    title: PaperMod RTL
    #    homeInfoParams:
    #        Title: "Hi there \U0001F44B"
    #        Content: Welcome to RTL layout
    #    menu:
    #        main:
    #            - name: Tags
    #              url: tags
    #              weight: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "fellas - a bcc guild on zandalar tribe-eu"
    author: fellas
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    # comments: false
    images: ["papermod-cover.png"]

    profileMode:
        enabled: true
        title: fellas
        imageUrl: "#"
        imageTitle: fellas
        imageWidth: 120
        imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
        Title: "fellas"
        Content: fellas are a bcc guild on zandalar tribe-eu

    socialIcons:
        - name: discord
          url: "https://discord.fellas.soy"
        - name: twitch
          url: "https://www.twitch.tv/bluepanchoyee"

    # editPost:
      #  URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
      #  Text: "Suggest Changes" # edit text
      #  appendFilePath: true # to append file path to Edit link

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    # assets:
    #     favicon: "favicon.ico"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
